#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

// Generated by Xcode for the Swift half of this pod; nitrogen's own bridge
// includes it the same way.
#if __has_include("OsukiSplash-Swift.h")
#import "OsukiSplash-Swift.h"
#elif __has_include(<OsukiSplash/OsukiSplash-Swift.h>)
#import <OsukiSplash/OsukiSplash-Swift.h>
#endif

/**
 * Registers the launch-screen manager before `main()` runs, so apps need no
 * AppDelegate changes. Swift cannot override `+load`, hence this shim.
 *
 * `UIApplicationDidFinishLaunchingNotification` is posted right after the
 * app delegate returns from `application:didFinishLaunchingWithOptions:`,
 * by which point React Native has created its window and root view. Scene
 * based apps create the window later; the manager also listens for
 * `UIWindowDidBecomeKeyNotification` and attaches then.
 */
@interface OsukiSplashLaunchHook : NSObject
@end

@implementation OsukiSplashLaunchHook

+ (void)load
{
  [[NSNotificationCenter defaultCenter] addObserverForName:UIApplicationDidFinishLaunchingNotification
                                                    object:nil
                                                     queue:[NSOperationQueue mainQueue]
                                                usingBlock:^(NSNotification *_Nonnull note) {
                                                  [[OsukiSplashScreenManager shared] applicationDidFinishLaunching];
                                                }];
}

@end
