import fs from 'node:fs'
import path from 'node:path'

import { ANDROID_ICON_CANVAS_DP, ANDROID_ICON_WARN_DP } from '../options'
import type { ResolvedSplash } from '../options'
import { composeOnCanvas, resolveAsset } from './image'
import type { ImageContext } from './image'

export const LOGO_DRAWABLE = 'splashscreen_logo'
export const BACKGROUND_COLOR = 'splashscreen_background'
export const SPLASH_THEME = 'Theme.App.SplashScreen'
export const SPLASH_THEME_PARENT = 'Theme.SplashScreen'
export const RUNTIME_RESOURCE_FILE = 'osuki_splash.xml'

const DENSITIES: Array<{ qualifier: string; multiplier: number }> = [
  { qualifier: 'mdpi', multiplier: 1 },
  { qualifier: 'hdpi', multiplier: 1.5 },
  { qualifier: 'xhdpi', multiplier: 2 },
  { qualifier: 'xxhdpi', multiplier: 3 },
  { qualifier: 'xxxhdpi', multiplier: 4 },
]

export interface AndroidGenerateContext extends ImageContext {
  /** `android/app/src/main/res` */
  resRoot: string
  warn?: (message: string) => void
}

export interface AndroidSplashOutput {
  /** Files written, relative to the res root. */
  files: string[]
  hasLogo: boolean
}

/**
 * Writes the density drawables (logo centred on a transparent 288 dp
 * canvas, light and night) plus the runtime resource file. Colours, styles
 * and the manifest theme are text edits done by the caller (Expo mods or the
 * CLI's XML helpers) because they live in files the app also owns.
 */
export async function generateAndroidDrawables(ctx: AndroidGenerateContext, splash: ResolvedSplash): Promise<AndroidSplashOutput> {
  const files: string[] = []
  const image = splash.image ? resolveAsset(ctx.projectRoot, splash.image) : undefined
  const darkImage = splash.darkImage ? resolveAsset(ctx.projectRoot, splash.darkImage) : undefined

  if (image && splash.imageWidth > ANDROID_ICON_WARN_DP) {
    ctx.warn?.(
      `[react-native-splash] imageWidth ${splash.imageWidth} dp is larger than the ${ANDROID_ICON_WARN_DP} dp that Android 12 shows uncropped; corners of a full-bleed logo will be masked.`,
    )
  }

  for (const { qualifier, multiplier } of DENSITIES) {
    for (const [file, folder] of [
      [image, `drawable-${qualifier}`],
      [darkImage, `drawable-night-${qualifier}`],
    ] as const) {
      const target = path.join(ctx.resRoot, folder, `${LOGO_DRAWABLE}.png`)
      fs.rmSync(target, { force: true })
      if (!file) continue
      fs.mkdirSync(path.dirname(target), { recursive: true })
      const logoSize = Math.round(splash.imageWidth * multiplier)
      const canvasSize = Math.round(ANDROID_ICON_CANVAS_DP * multiplier)
      fs.writeFileSync(target, await composeOnCanvas(ctx, file, logoSize, canvasSize))
      files.push(path.relative(ctx.resRoot, target))
    }
  }

  const runtime = path.join(ctx.resRoot, 'values', RUNTIME_RESOURCE_FILE)
  fs.mkdirSync(path.dirname(runtime), { recursive: true })
  fs.writeFileSync(runtime, buildRuntimeResources(splash))
  files.push(path.relative(ctx.resRoot, runtime))

  return { files, hasLogo: image !== undefined }
}

/** `res/values/osuki_splash.xml`: what native reads back at runtime. */
export function buildRuntimeResources(splash: ResolvedSplash): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by @osuki-dev/react-native-splash. Do not edit; rerun the generator. -->
<resources>
  <bool name="osuki_splash_auto_hide">${splash.autoHide}</bool>
  <integer name="osuki_splash_hide_timeout_ms">${Math.round(splash.hideTimeoutMs)}</integer>
</resources>
`
}

/** The `<style>` items for `Theme.App.SplashScreen`. */
export function splashStyleItems(splash: ResolvedSplash, hasLogo: boolean): Array<{ name: string; value: string }> {
  const items = [{ name: 'windowSplashScreenBackground', value: `@color/${BACKGROUND_COLOR}` }]
  if (hasLogo) items.push({ name: 'windowSplashScreenAnimatedIcon', value: `@drawable/${LOGO_DRAWABLE}` })
  items.push({ name: 'postSplashScreenTheme', value: `@style/${splash.postTheme}` })
  // API 33+: keep the icon even when the launcher asks for a plain colour.
  items.push({ name: 'android:windowSplashScreenBehavior', value: 'icon_preferred' })
  return items
}
